// scripts/build-icons.js - Bundle only the Lucide icons the app actually uses.
// Scans index.html and js/*.js for icon names and writes js/icons.js, which exposes
// the same `window.lucide.createIcons()` API the app used with the full CDN build.
// Run: npm run build:icons
const fs = require('fs');
const path = require('path');
const lucide = require('lucide/dist/umd/lucide.js');

const ROOT = path.join(__dirname, '..');
const OUT_FILE = path.join(ROOT, 'js/icons.js');
const SOURCES = [
  path.join(ROOT, 'index.html'),
  ...fs.readdirSync(path.join(ROOT, 'js'))
    .filter(f => f.endsWith('.js') && f !== 'icons.js')
    .map(f => path.join(ROOT, 'js', f))
];

const toPascalCase = name => name.split(/[-_]/).filter(Boolean)
  .map(part => part[0].toUpperCase() + part.slice(1)).join('');

// data-lucide="name" plus names chosen in template expressions: data-lucide="${cond ? 'a' : 'b'}"
const names = new Set();
for (const file of SOURCES) {
  const src = fs.readFileSync(file, 'utf8');
  for (const m of src.matchAll(/data-lucide="([^"]+)"/g)) {
    const value = m[1];
    if (value.includes('${')) {
      for (const q of value.matchAll(/'([a-z0-9-]+)'/g)) names.add(q[1]);
    } else {
      names.add(value);
    }
  }
}

const icons = {};
const missing = [];
for (const name of [...names].sort()) {
  const node = lucide.icons[toPascalCase(name)];
  if (node) icons[name] = node; else missing.push(name);
}
if (missing.length) {
  console.error(`[build-icons] Unknown Lucide icons: ${missing.join(', ')}`);
  process.exit(1);
}

const version = require('lucide/package.json').version;
const output = `// js/icons.js - GENERATED by scripts/build-icons.js from lucide@${version}. Do not edit by hand.
// Contains only the ${Object.keys(icons).length} icons used by the app; mirrors lucide.createIcons().
(function (window) {
  var ICONS = ${JSON.stringify(icons)};
  var DEFAULTS = { xmlns: 'http://www.w3.org/2000/svg', width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' };
  var SVG_NS = 'http://www.w3.org/2000/svg';

  function build(tag, attrs, children) {
    var el = document.createElementNS(SVG_NS, tag);
    Object.keys(attrs).forEach(function (k) { el.setAttribute(k, String(attrs[k])); });
    (children || []).forEach(function (c) { el.appendChild(build(c[0], c[1], c[2])); });
    return el;
  }

  function replaceElement(el) {
    var name = el.getAttribute('data-lucide');
    var node = ICONS[name];
    if (!node) return console.warn(el.outerHTML + ' icon name was not found in the provided icons object.');
    var own = {};
    var hasA11y = false;
    Array.prototype.forEach.call(el.attributes, function (a) {
      own[a.name] = a.value;
      if (a.name.indexOf('aria-') === 0 || a.name === 'role' || a.name === 'title') hasA11y = true;
    });
    var attrs = Object.assign({}, DEFAULTS, { 'data-lucide': name }, hasA11y ? {} : { 'aria-hidden': 'true' }, own);
    var classes = ['lucide', 'lucide-' + name].concat(own['class'] ? own['class'].split(' ') : []);
    attrs['class'] = classes.filter(function (c, i, arr) { return c && c.trim() !== '' && arr.indexOf(c) === i; }).join(' ').trim();
    if (el.parentNode) el.parentNode.replaceChild(build('svg', attrs, node), el);
  }

  function createIcons(opts) {
    var root = (opts && opts.root) || document;
    Array.prototype.forEach.call(root.querySelectorAll('[data-lucide]'), replaceElement);
  }

  window.lucide = { createIcons: createIcons };
})(window);
`;
fs.writeFileSync(OUT_FILE, output);
console.log(`[build-icons] Wrote ${path.relative(ROOT, OUT_FILE)}: ${Object.keys(icons).length} icons, ${output.length} bytes`);
